/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module top (
  input paro_boton,
  output control,
  output paro_led,
  output sol,
  output bateria,
  output red
);
  assign red = ~paro_boton;
  assign sol = 1;
  assign bateria = 1;
  assign control = ~paro_boton;
  assign paro_led = paro_boton;
endmodule
